-- Migration: Improve referrer tracking in BH get_analytics_data()
-- Apply to: brasilhorizonte (dawvgbopyemcayavcatd)
-- Changes:
--   - Separate Gmail from Google Search (Email vs Google)
--   - Add categories: Stripe, Lovable (Dev), Localhost (Dev), Email
--   - Add social media: Reddit, LinkedIn, Twitter/X, Facebook, Instagram, YouTube, WhatsApp, Telegram
--   - Add referrer_detail: top raw URLs (excluding dev/internal)
--   - Add referrer_daily: daily breakdown by source for trend analysis
--   - Fix top_tickers_market and sector_distribution to use brapi_quotes table
--   - Use GROUP BY 1 for CASE alias compatibility

-- See full RPC in apply_migration call (too large to duplicate here)
-- Key referrer categories:
--   Direto, Email, Google, Facebook, Instagram, Twitter/X, LinkedIn, Reddit,
--   YouTube, WhatsApp, Telegram, Stripe, Lovable (Dev), Localhost (Dev), Interno, Outro
